-- -- Users table seeds here (Example)
-- INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (2,'Madona@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (2,'Madona@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (2,'Madona@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (2,'Madona@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (2,'Madona@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.yahoofinance.co.uk');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (1,'seanPaul@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (1,'seanPaul@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (1,'seanPaul@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (1,'seanPaul@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (1,'seanPaul@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.yahoofinance.co.uk');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (3,'britneySpears@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (3,'britneySpears@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (3,'britneySpears@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (3,'britneySpears@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (4,'dougFord@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (4,'dougFord@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (4,'dougFord@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (4,'dougFord@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (5,'donald@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (5,'donald@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (5,'donald@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (5,'donald@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com')
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (6,'joeBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.netflix.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (6,'joeBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (6,'joeBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (6,'joeBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (6,'joeBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.yahoofinance.co.uk');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (7,'hunterBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.facebook.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (7,'hunterBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.gmail.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (7,'hunterBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.espn.com');
INSERT INTO user_login_per_site (user_id, user_name_for_site_login, user_password_for_site_login, url_for_login) VALUES (7,'hunterBiden@email.com','$2a$10$J.Q35an9AC7GZLm0EKT.FuwDXuCq2zhh83WrMC6WSxvE63ocYnioa','www.yahoofinance.co.uk');

